### ISSUE TITLE
using RUVg on ERRC spike ins for DE analysis where we expect a global amplification of transcription in one group

### ISSUE THREAD

**Issue by LouellaVasquez33** [drisso/RUVSeq#9] opened 2021-06-16 10:14 UTC
Hello, 

We are interested in finding DE genes where  one group has undergone a treatment that caused a global depletion of heterochromatin histone marks which may lead to global amplification of transcription.
I am using edgeR for DE analysis.

Following the RUVSeq vignettte, I am planning to use  RUVg on negative controls, i.e., ERCC spike ins, then
to add the W matrix as covariates in the design matrix.

I do not want to remove the presence of the global amplification in transcription.
Do I then not use a library size scaling factor (eg, TMM on endogenous genes in edgeR), in which case the W matrix will be the only normalisation  for the read counts?

Looking forward to your reply.

Many thanks!
Louella

**Comment by drisso** [comment] 2021-06-21 20:59
Hi @LouellaVasquez33 ,

if you expect global amplification, my suggestion is to skip the scaling normalization and only use W for normalization. 

Keep in mind that you will essentially not normalize for sequencing depth, i.e., you assume that the difference in total reads assigned to endogenous genes between samples is due to real biological differences and not technical bias. You are making a big assumption here, i.e., that the spike-ins will capture the full extent of technical bias in the library prep. We know this is not the case, but in this case it's the least of the two evil, I think.

**Closed as completed by drisso** 2021-06-21 20:59 UTC

**Comment by tycho-kirchner** [comment] 2025-03-27 21:51
Thanks for the clarification @drisso. So, adapting the example from the vignette, are you in fact suggesting to set DESeq2's sizefactors to 1, i.e.
~~~
library(DESeq2)
dds <- DESeqDataSetFromMatrix(countData = counts(set1),
                              colData = pData(set1),
                              design = ~ W_1 + x)
sizeFactors(dds) =  1.0
dds <- DESeq(dds)
~~~

I tried this on an ERCC-spiked dataset with a (also otherwise) confirmed transcriptional shutdown and noticed a mixed performance. In particular, the number of DEGs is quite different, when setting the sizefactors via `sizeFactors(dds)=1.0` , `estimateSizeFactors` having applied W_1 beforehand and `estimateSizeFactors` without W_1.
~~~
idxVector= rownames(dds) %in% spikes
dds = estimateSizeFactors(dds, controlGenes=idxVector)
~~~

I attached the self-generated count table of the study[^1], in case you would like to take a look. Here are the various results:
~~~
# sizeFactors(dds)=1.0`, with W_1
Vector-vs-4K-A:  up 48 down 589
Vector-vs-R546Q: up 23 down 971
Vector-vs-WT:    up 12 down 6352


# estimateSizeFactors using spike-ins, with W_1
Vector-vs-4K-A   up 46 down 2429
Vector-vs-R546Q  up 24 down 3819
Vector-vs-WT     up 12 down 8279


# estimateSizeFactors using spike-ins, without W_1
Vector-vs-4K-A  up 213 down 8608
Vector-vs-R546Q up 94  down 9285
Vector-vs-WT    up 98  down 15800
~~~

How should RUVSeq be applied here? Thanks and kind Regards
Tycho

[exp.htsc.gz](https://github.com/user-attachments/files/19494557/exp.htsc.gz)

[^1]: Lau, M.S., Hu, Z., Zhao, X., Tan, Y.S., Liu, J., Huang, H., Yeo, C.J., Leong, H.F., Grinchuk, O.V., Chan, J.K., et al. (2023). Transcriptional repression by a secondary DNA binding surface of DNA topoisomerase I safeguards against hypertranscription. Nat Commun 14, 6464. https://doi.org/10.1038/s41467-023-42078-9.
